package(default_visibility = [
    "//visibility:public",
])

exports_files([
    "Launch.storyboard",
    "Main.storyboard",
    "listings.plist",
])

filegroup(
    name = "Images",
    srcs = glob(["images/*.jpeg"]),
)
