package(default_visibility = [
    "//visibility:public",
])

exports_files([
    "Launch.storyboard",
    "Main.storyboard",
])

filegroup(
   name = "CoreDataModel.xcdatamodeld",
   srcs = glob(["CoreDataModel.xcdatamodeld/**"]),
)
